[[plugins]]

package = "netlify-plugin-flutter"

[plugins.inputs]
channel = "stable"

[build]

command = "flutter build web --web-renderer canvaskit --release"
publish = "build/web"

[build.environment]
FLUTTER_VERSION = "3.22.0"