# This file configures the analyzer to use the lint rule set from `package:lint`
include: package:lint/analysis_options.yaml

analyzer:
  exclude:

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
